apiVersion: v2
name: rustdesk-server
description: A production-ready Helm chart for deploying RustDesk Server on Kubernetes.
type: application

version: 0.1.0
appVersion: "1.1.16"

keywords:
  - rustdesk
  - rustdesk-server
  - remote-desktop
  - remote-access
  - self-hosted

home: https://github.com/mohrezfadaei/rustdesk-server-helm

sources:
  - https://github.com/mohrezfadaei/rustdesk-server-helm
  - https://github.com/rustdesk/rustdesk-server

maintainers:
  - name: Mohamad Reza Fadaei
    email: mohrezfadaei@gmail.com

icon: https://github.com/mohrezfadaei/rustdesk-server-helm/blob/main/assets/icon.png

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: source
      url: https://github.com/mohrezfadaei/rustdesk-server-helm
    - name: support
      url: https://github.com/mohrezfadaei/rustdesk-server-helm/issues
    - name: RustDesk
      url: https://github.com/rustdesk/rustdesk
  artifacthub.io/changes: |
    - Initial release of the RustDesk Server Helm chart
