{{- if include "rustdesk-server.createKeySecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rustdesk-server.secretName" . }}
  namespace: {{ include "rustdesk-server.namespace" . | quote }}
  labels: {{- include "rustdesk-server.labels" (dict "context" $) | nindent 4 }}
  {{- if or .Values.auth.annotations .Values.commonAnnotations }}
  annotations:
    {{- with .Values.auth.annotations }}
    {{- include "rustdesk-server.tplvalues" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
    {{- include "rustdesk-server.tplvalues" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
data:
  {{ .Values.auth.privateKeySecretKey }}: {{ .Values.auth.privateKey | b64enc | quote }}
  {{ .Values.auth.publicKeySecretKey }}: {{ .Values.auth.publicKey | b64enc | quote }}
{{- end }}
