{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rustdesk-server.serviceAccountName" . }}
  namespace: {{ include "rustdesk-server.namespace" . | quote }}
  labels: {{- include "rustdesk-server.labels" (dict "context" $) | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}
    {{- include "rustdesk-server.tplvalues" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
  {{- if or .Values.serviceAccount.annotations .Values.commonAnnotations }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- include "rustdesk-server.tplvalues" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
    {{- include "rustdesk-server.tplvalues" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
